version: '3.7'

services:
  web:
    build: ./
    command: gunicorn wherefilmed.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/

    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
  db:
    image: mysql:8.0.29
    restart: always
    volumes:
      - my-db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: Mkm695nbv45fa8phg
      MYSQL_PASSWORD: Mkm695nbv45fa8phg
      MYSQL_USER: ugrobug
      MYSQL_DATABASE: wherefilmed
    expose:
      - 8800
    env_file:
      - ./.env.prod.db
volumes:
  my-db: