# Generated by Django 4.0.4 on 2022-05-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='start_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='end_year',
        ),
    ]
