# Generated by Django 4.0.4 on 2022-06-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_start_year_movies_year_remove_movies_end_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.locations')),
            ],
        ),
    ]
