# Generated by Django 4.0.4 on 2022-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_locationsgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsgallery',
            name='image',
        ),
        migrations.AddField(
            model_name='locationsgallery',
            name='movie',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='locationsgallery',
            name='real_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
