# Generated by Django 4.0.4 on 2022-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_locationsgallerymovie_locationsgalleryreal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'сountry', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Country'),
        ),
    ]
