# Generated by Django 4.0.4 on 2022-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_country_options_alter_country_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'сountry', 'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='country_description',
            field=models.TextField(blank=True, null=True, verbose_name='Country Description'),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.TextField(blank=True, null=True, verbose_name='Genre description'),
        ),
    ]
