# Generated by Django 4.0.4 on 2022-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_country_options_country_country_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='country',
        ),
        migrations.AddField(
            model_name='movies',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='movies.country'),
        ),
    ]
