# Generated by Django 4.0.4 on 2022-06-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movies_country_movies_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movies.genre'),
        ),
    ]
