# Generated by Django 4.0.4 on 2022-06-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_locations_address_alter_locations_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.ManyToManyField(blank=True, to='movies.country'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(blank=True, to='movies.genre'),
        ),
    ]
