# Generated by Django 4.0.4 on 2022-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_movies_country_alter_movies_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='movies.country'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movies.genre'),
        ),
    ]
