# Generated by Django 4.0.4 on 2022-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movies_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
