# Generated by Django 4.0.4 on 2022-06-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_country_slug_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsgallerymovie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='locationsgalleryreal',
            name='real_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(upload_to='gallery/%Y-%m-%d/', verbose_name='Poster'),
        ),
    ]
